import type { Region } from "./types";

export const REGIONS: Region[] = [
  // Tier 1 - live sub-hourly
  { id: "caiso",            name: "California",      country: "USA", lat: 36.5, lon: -119.5, tier: "live", kind: "mixed", source: "CAISO OASIS / EIA (solar+wind)", sourceUrl: "https://oasis.caiso.com/oasisapi" },
  { id: "ercot-west",       name: "ERCOT West",      country: "USA", lat: 33.5, lon: -102.0, tier: "live", kind: "mixed", source: "EIA / ERCOT (wind+solar)", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  { id: "ercot-east",       name: "ERCOT East",      country: "USA", lat: 31.8, lon:  -99.9, tier: "live", kind: "mixed", source: "EIA / ERCOT (wind+solar)", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  { id: "miso",             name: "MISO (Midwest)",  country: "USA", lat: 41.5, lon:  -93.0, tier: "live", kind: "mixed", source: "EIA MISO wind+solar", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  { id: "pjm",              name: "PJM",             country: "USA", lat: 40.0, lon:  -77.0, tier: "live", kind: "mixed", source: "EIA PJM wind+solar", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  { id: "spp",              name: "SPP",             country: "USA", lat: 38.0, lon:  -98.0, tier: "live", kind: "mixed", source: "EIA SPP wind+solar", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  // NYISO split into zones D+E (North Country / Mohawk Valley — bulk of wind
  // curtailment per NYISO Power Trends 2024 / Unbottling Wind) vs the rest.
  // 2023 statewide wind curtailment was 0.162 TWh, concentrated in D/E.
  { id: "nyiso-zones-d-e",  name: "NYISO Zones D+E", country: "USA", lat: 43.7, lon:  -75.3, tier: "live", kind: "wind",  source: "EIA NYISO wind (Zones D+E share, ~75% of statewide curtailment)", sourceUrl: "https://www.nyiso.com/documents/20142/2223020/2024-Power-Trends.pdf" },
  { id: "nyiso-rest",       name: "NYISO (rest)",    country: "USA", lat: 42.8, lon:  -74.8, tier: "live", kind: "mixed", source: "EIA NYISO wind+solar (ex-Zones D/E)", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  // ISO-NE split — ISO-NE IMM's 2024 annual markets report says 93% of
  // 2020-2024 curtailed renewable capacity in New England was in Maine and
  // Vermont (northern congestion pocket). 2024 ISO-NE renewable curtailment
  // total = 0.034 TWh, split 93/7.
  { id: "iso-ne-maine-vermont", name: "ISO-NE Maine/Vermont", country: "USA", lat: 44.7, lon: -70.6, tier: "live", kind: "wind",  source: "EIA ISO-NE wind (ME+VT share, 93% of NE curtailment per IMM)", sourceUrl: "https://www.iso-ne.com/static-assets/documents/100023/2024-annual-markets-report.pdf" },
  { id: "iso-ne-rest",          name: "ISO-NE (rest)",        country: "USA", lat: 42.2, lon: -71.8, tier: "live", kind: "mixed", source: "EIA ISO-NE wind+solar (ex-ME/VT)", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  { id: "bpa",              name: "BPA",             country: "USA", lat: 45.7, lon: -121.5, tier: "live", kind: "mixed", source: "EIA BPA wind+solar", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  { id: "aemo-nsw-wind",    name: "New South Wales Wind",  country: "AUS", lat: -32.5, lon: 146.2, tier: "live", kind: "wind",  source: "AEMO NEMWeb wind SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-nsw-solar",   name: "New South Wales Solar", country: "AUS", lat: -32.2, lon: 146.8, tier: "live", kind: "solar", source: "AEMO NEMWeb solar SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-vic-wind",    name: "Victoria Wind",         country: "AUS", lat: -37.0, lon: 144.5, tier: "live", kind: "wind",  source: "AEMO NEMWeb wind SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-vic-solar",   name: "Victoria Solar",        country: "AUS", lat: -36.7, lon: 145.1, tier: "live", kind: "solar", source: "AEMO NEMWeb solar SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-qld-wind",    name: "Queensland Wind",       country: "AUS", lat: -22.0, lon: 144.7, tier: "live", kind: "wind",  source: "AEMO NEMWeb wind SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-qld-solar",   name: "Queensland Solar",      country: "AUS", lat: -21.7, lon: 145.3, tier: "live", kind: "solar", source: "AEMO NEMWeb solar SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-sa-wind",     name: "South Australia Wind",  country: "AUS", lat: -33.0, lon: 137.7, tier: "live", kind: "wind",  source: "AEMO NEMWeb wind SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-sa-solar",    name: "South Australia Solar", country: "AUS", lat: -32.7, lon: 138.3, tier: "live", kind: "solar", source: "AEMO NEMWeb solar SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-tas-wind",    name: "Tasmania Wind",         country: "AUS", lat: -42.0, lon: 146.5, tier: "live", kind: "wind",  source: "AEMO NEMWeb wind SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "aemo-tas-solar",   name: "Tasmania Solar",        country: "AUS", lat: -41.7, lon: 147.1, tier: "live", kind: "solar", source: "AEMO NEMWeb solar SEMIDISPATCHCAP", sourceUrl: "https://nemweb.com.au/Reports/Current/Next_Day_Dispatch/" },
  { id: "belgium",          name: "Belgium",         country: "BEL", lat: 50.5, lon:    4.5, tier: "live", kind: "mixed", source: "Elia Open Data (wind+solar)", sourceUrl: "https://opendata.elia.be/" },
  { id: "iberia",           name: "Iberia",          country: "ESP", lat: 39.5, lon:   -3.5, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "portugal",         name: "Portugal",        country: "PRT", lat: 39.5, lon:   -8.0, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "germany",          name: "Germany",         country: "DEU", lat: 52.5, lon:   10.5, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "finland",          name: "Finland",         country: "FIN", lat: 62.0, lon:   25.0, tier: "live", kind: "wind",  source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "france",           name: "France",          country: "FRA", lat: 46.5, lon:    2.5, tier: "live", kind: "mixed", source: "RTE eco2mix wind+solar", sourceUrl: "https://odre.opendatasoft.com/" },
  // Netherlands rate is a TenneT BritNed/COBRA cross-border-loss share rather
  // than a directly-published curtailment-as-fraction-of-generation; counted
  // as T1b live-domestic-anchored per B4 Option B (locked 2026-04-25). See
  // docs/proposals/b4-option-b-decision.md §"Post-B1 rerun (2026-04-26)".
  { id: "netherlands",      name: "Netherlands",     country: "NLD", lat: 52.2, lon:    5.3, tier: "live-domestic-anchored", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  // Denmark split by Energinet PriceArea. DK1 (Jutland/Fyn) hosts most
  // onshore wind and is interconnected to Germany; DK2 (Zealand) sits
  // across the Øresund from Sweden. Energi Data Service is natively zonal;
  // split 75/25 reflects DK1's share of combined wind+solar generation.
  { id: "denmark-west",      name: "Denmark DK1",     country: "DNK", lat: 56.2, lon:    9.1, tier: "live", kind: "mixed", source: "Energinet wind+solar (DK1)", sourceUrl: "https://api.energidataservice.dk/" },
  { id: "denmark-east",      name: "Denmark DK2",     country: "DNK", lat: 55.4, lon:   12.3, tier: "live", kind: "mixed", source: "Energinet wind+solar (DK2)", sourceUrl: "https://api.energidataservice.dk/" },
  { id: "poland",           name: "Poland",          country: "POL", lat: 52.0, lon:   19.0, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "greece",           name: "Greece",          country: "GRC", lat: 39.0, lon:   22.0, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "romania",          name: "Romania",         country: "ROU", lat: 45.9, lon:   25.0, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "turkey",           name: "Turkey",          country: "TUR", lat: 39.0, lon:   35.0, tier: "live", kind: "mixed", source: "EPIAS Transparency dashboard wind+solar", sourceUrl: "https://seffaflik.epias.com.tr/electricity-service/v1/dashboard/realtime-generation" },
  // italy-north-zone uses a Terna national-MSD-share rate rather than a
  // North-zone-specific MSD figure; T1b live-domestic-anchored per B4
  // Option B (modelled-share scope mismatch).
  { id: "italy-north-zone", name: "Italy North",     country: "ITA", lat: 45.0, lon:   10.0, tier: "live-domestic-anchored", kind: "mixed", source: "ENTSO-E Terna (North zone)", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "italy-sicily",    name: "Sicily",          country: "ITA", lat: 37.6, lon:   14.0, tier: "live-domestic-anchored", kind: "mixed", source: "ENTSO-E Terna (Sicily)", sourceUrl: "https://transparency.entsoe.eu/" },
  // italy-sardinia uses the Terna national MSD rate scaled to Sardinia's
  // wind+PV share — a modelled-share split that captures the wrong scope.
  // T1b live-domestic-anchored per B4 Option B (post-B1 P67 +87.6% residual).
  { id: "italy-sardinia",  name: "Sardinia",        country: "ITA", lat: 40.1, lon:    9.1, tier: "live-domestic-anchored", kind: "mixed", source: "ENTSO-E Terna (Sardinia)", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "sweden-north",     name: "Sweden North",    country: "SWE", lat: 63.5, lon:   18.5, tier: "live", kind: "wind",  source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "sweden-south",     name: "Sweden South",    country: "SWE", lat: 56.0, lon:   14.0, tier: "live", kind: "mixed", source: "ENTSO-E", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "ukraine",          name: "Ukraine",         country: "UKR", lat: 48.38, lon: 31.17, tier: "static", kind: "solar", source: "Ember Ukraine 2024 (ENTSO-E absent post-war)", sourceUrl: "https://ember-energy.org/global-insights/ukraine-electricity-tracker/" },
  { id: "hungary",          name: "Hungary",         country: "HUN", lat: 47.16, lon: 19.50, tier: "live", kind: "mixed", source: "ENTSO-E MAVIR", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "czech-republic",   name: "Czech Republic",  country: "CZE", lat: 49.82, lon: 15.47, tier: "live", kind: "mixed", source: "ENTSO-E CEPS", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "bulgaria",         name: "Bulgaria",        country: "BGR", lat: 42.73, lon:   25.49, tier: "live", kind: "mixed", source: "ENTSO-E ESO", sourceUrl: "https://transparency.entsoe.eu/" },
  // Serbia — EMS A75 feed; regional default (solar 2%, wind 3%) per methodology.
  // No published Serbian curtailment anchor found.
  { id: "serbia",           name: "Serbia",          country: "SRB", lat: 44.00, lon:   21.00, tier: "live", kind: "mixed", source: "ENTSO-E EMS", sourceUrl: "https://transparency.entsoe.eu/" },
  // Bosnia and Herzegovina — JPCC A75 feed; hydro-dominated. Structural
  // hydro spill excluded per methodology; no VRE curtailment rate published.
  { id: "bosnia-and-herzegovina", name: "Bosnia & Herzegovina", country: "BIH", lat: 43.90, lon:   18.00, tier: "live", kind: "hydro", source: "ENTSO-E JPCC (Krajina)", sourceUrl: "https://transparency.entsoe.eu/" },
  // North Macedonia — MEPSO A75 feed; regional defaults (solar 2%, wind 3%).
  { id: "north-macedonia",  name: "North Macedonia",  country: "MKD", lat: 41.50, lon:   22.00, tier: "live", kind: "mixed", source: "ENTSO-E MEPSO", sourceUrl: "https://transparency.entsoe.eu/" },
  // Montenegro — CGES A75 feed; hydro-dominated. Structural hydro spill
  // excluded per methodology; no VRE curtailment rate published.
  { id: "montenegro",       name: "Montenegro",       country: "MNE", lat: 42.50, lon:   19.30, tier: "live", kind: "hydro", source: "ENTSO-E CGES", sourceUrl: "https://transparency.entsoe.eu/" },
  // Croatia — HOPS A75 feed; regional defaults (solar 2%, wind 2.5%).
  { id: "croatia",          name: "Croatia",          country: "HRV", lat: 45.10, lon:   15.50, tier: "live", kind: "mixed", source: "ENTSO-E HOPS", sourceUrl: "https://transparency.entsoe.eu/" },
  // Slovenia — ELES A75 feed; regional defaults (solar 2%, wind 2%).
  { id: "slovenia",         name: "Slovenia",         country: "SVN", lat: 46.12, lon:   14.82, tier: "live", kind: "mixed", source: "ENTSO-E ELES", sourceUrl: "https://transparency.entsoe.eu/" },
  // Slovakia — SEPS A75 feed; regional defaults (solar 2.5%, wind 2%).
  { id: "slovakia",         name: "Slovakia",         country: "SVK", lat: 48.67, lon:   19.50, tier: "live", kind: "mixed", source: "ENTSO-E SEPS", sourceUrl: "https://transparency.entsoe.eu/" },
  // Lithuania — Litgrid A75 feed; wind-dominant, solar negligible.
  // Wind rate anchored to Litgrid 2024 published curtailment.
  { id: "lithuania",        name: "Lithuania",        country: "LTU", lat: 55.17, lon:   23.88, tier: "live", kind: "wind", source: "ENTSO-E Litgrid", sourceUrl: "https://transparency.entsoe.eu/" },
  // Latvia — AST A75 feed; wind 2.5% regional default (consistent with lithuania/estonia).
  { id: "latvia",           name: "Latvia",           country: "LVA", lat: 56.88, lon:   24.60, tier: "live", kind: "wind", source: "ENTSO-E AST", sourceUrl: "https://transparency.entsoe.eu/" },
  // Estonia — Elering A75 feed; wind 2.5% regional default. Replaces legacy
  // `baltics` T1b region (which was a Lithuania-only feed mislabelled as a
  // Baltic aggregate). EE wind is the dispatch-curtailable component; PV is
  // dominated by behind-meter distributed generation that does not appear in A75.
  { id: "estonia",          name: "Estonia",          country: "EST", lat: 58.60, lon:   25.01, tier: "live", kind: "wind", source: "ENTSO-E Elering", sourceUrl: "https://transparency.entsoe.eu/" },
  // Luxembourg — Cegedel A75 feed; small grid, PV+wind <0.5 GW. Regional defaults.
  { id: "luxembourg",       name: "Luxembourg",       country: "LUX", lat: 49.80, lon:    6.10, tier: "live", kind: "mixed", source: "ENTSO-E Cegedel", sourceUrl: "https://transparency.entsoe.eu/" },
  // Malta — Enemalta A75 feed; PV-dominant island grid. Solar 2% regional default.
  { id: "malta",            name: "Malta",            country: "MLT", lat: 35.94, lon:   14.40, tier: "live", kind: "solar", source: "ENTSO-E Enemalta", sourceUrl: "https://transparency.entsoe.eu/" },
  // Moldova — Moldelectrica A75 via MEPSO protocol; not ENTSO-E-synchronised.
  // Cross-border coordination with UA/RO. Regional defaults (no anchor found).
  { id: "moldova",          name: "Moldova",          country: "MDA", lat: 47.00, lon:   28.50, tier: "live", kind: "mixed", source: "ENTSO-E Moldelectrica (MEPSO protocol)", sourceUrl: "https://transparency.entsoe.eu/" },
  // GB split — NESO Markets Roadmap 2024 reports ~11 TWh/yr of constraint
  // actions, dominated by the Scotland-to-England export boundary. Split
  // 70/30 at consumption: Scotland carries the bulk of curtailed wind.
  { id: "gb-scotland",      name: "GB Scotland",     country: "GBR", lat: 56.8, lon:   -4.2, tier: "live", kind: "wind",  source: "Elexon BMRS wind+solar (Scotland share, ~70% via NESO constraint boundary)", sourceUrl: "https://www.neso.energy/data-portal/monthly-operational-metered-wind-output" },
  { id: "gb-england-wales", name: "GB England+Wales", country: "GBR", lat: 52.9, lon:  -1.8, tier: "live", kind: "mixed", source: "Elexon BMRS wind+solar (England+Wales share)", sourceUrl: "https://www.elexon.co.uk/data/" },
  // Brazil ONS constrained-off split by state and technology. The loader
  // fetches ONS wind and solar CSV families separately, so dashboard rows
  // remain single-fuel instead of using a bundled wind+solar state bar.
  { id: "brazil-rn-wind",        name: "Rio Grande do Norte Wind", country: "BRA", lat: -5.8, lon: -36.5, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-rn-solar",       name: "Rio Grande do Norte Solar", country: "BRA", lat: -5.6, lon: -36.1, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-ce-wind",        name: "Ceara Wind",                country: "BRA", lat: -5.0, lon: -39.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-ce-solar",       name: "Ceara Solar",               country: "BRA", lat: -4.8, lon: -38.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-bahia-wind",     name: "Bahia Wind",                country: "BRA", lat: -11.0, lon: -41.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-bahia-solar",    name: "Bahia Solar",               country: "BRA", lat: -10.8, lon: -40.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-piaui-wind",     name: "Piaui Wind",                country: "BRA", lat: -8.0, lon: -43.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-piaui-solar",    name: "Piaui Solar",               country: "BRA", lat: -7.8, lon: -42.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-pernambuco-wind", name: "Pernambuco Wind",          country: "BRA", lat: -8.0, lon: -37.7, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-pernambuco-solar", name: "Pernambuco Solar",        country: "BRA", lat: -7.8, lon: -37.3, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-paraiba-wind",   name: "Paraiba Wind",              country: "BRA", lat: -7.1, lon: -36.9, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-paraiba-solar",  name: "Paraiba Solar",             country: "BRA", lat: -6.9, lon: -36.5, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-maranhao-wind",  name: "Maranhao Wind",             country: "BRA", lat: -5.0, lon: -45.5, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-maranhao-solar", name: "Maranhao Solar",            country: "BRA", lat: -4.8, lon: -45.1, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-other-wind",     name: "Brazil Other ONS States Wind", country: "BRA", lat: -18.0, lon: -50.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-other-solar",    name: "Brazil Other ONS States Solar", country: "BRA", lat: -17.8, lon: -49.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  // Norway split into 5 ENTSO-E bidding zones (2026-04-24). Prior
  // `n-norway` aggregated only NO4 — the northern export-constrained
  // zone — and left ~80% of Norwegian renewable generation unmodelled,
  // including NO2 which hosts the Sørlige Nordsjø II offshore wind
  // programme and the landing points for NorNed, NordLink, and the
  // North Sea Link interconnectors. Lat/lon are zone centroids.
  { id: "norway-no1",       name: "Norway NO1 (Oslo)",         country: "NOR", lat: 59.9, lon:   10.7, tier: "live", kind: "mixed", source: "ENTSO-E NO1 hydro+wind (load-centre, low curtailment)", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "norway-no2",       name: "Norway NO2 (Kristiansand)", country: "NOR", lat: 58.2, lon:    7.6, tier: "live", kind: "mixed", source: "ENTSO-E NO2 hydro+offshore wind (NorNed/NordLink/NSL cable zone)", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "norway-no3",       name: "Norway NO3 (Trondheim)",    country: "NOR", lat: 63.4, lon:   10.4, tier: "live", kind: "mixed", source: "ENTSO-E NO3 hydro+onshore wind", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "norway-no4",       name: "Norway NO4 (Tromsø)",       country: "NOR", lat: 68.5, lon:   17.5, tier: "live", kind: "mixed", source: "ENTSO-E NO4 hydro+wind (export-constrained north; former n-norway)", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "norway-no5",       name: "Norway NO5 (Bergen)",       country: "NOR", lat: 60.4, lon:    5.3, tier: "live", kind: "hydro", source: "ENTSO-E NO5 reservoir hydro (spring-spill only)", sourceUrl: "https://transparency.entsoe.eu/" },
  // Switzerland — PV-only ENTSO-E feed via Swissgrid. Hydro spill is
  // not captured in A75 data, so this understates total Swiss
  // curtailment but captures the fastest-growing summer-midday PV
  // oversupply component. The calibration rate is extrapolated from
  // the Czech Republic CEPS rate (no domestic Swiss rate is published),
  // so this is T1c live-neighbour-anchored per B4 Option B (post-B1
  // empirical residual −35.5%).
  { id: "switzerland",      name: "Switzerland",     country: "CHE", lat: 46.8, lon:    8.2, tier: "live-neighbour-anchored", kind: "solar", source: "ENTSO-E Swissgrid PV-only (hydro spill not in A75)", sourceUrl: "https://transparency.entsoe.eu/" },
  { id: "ontario-wind",     name: "Ontario Wind",    country: "CAN", lat: 44.0, lon:  -81.0, tier: "live", kind: "wind",  source: "IESO wind generation capability", sourceUrl: "https://reports-public.ieso.ca/public/GenOutputCapability/" },
  { id: "ontario-solar",    name: "Ontario Solar",   country: "CAN", lat: 43.8, lon:  -80.5, tier: "live", kind: "solar", source: "IESO solar generation capability", sourceUrl: "https://reports-public.ieso.ca/public/GenOutputCapability/" },
  { id: "alberta-wind",     name: "Alberta Wind",    country: "CAN", lat: 51.5, lon: -114.0, tier: "live", kind: "wind",  source: "AESO wind snapshot", sourceUrl: "http://ets.aeso.ca/ets_web/ip/Market/Reports/CSDReportServlet" },
  { id: "alberta-solar",    name: "Alberta Solar",   country: "CAN", lat: 51.0, lon: -113.5, tier: "live", kind: "solar", source: "AESO solar snapshot", sourceUrl: "http://ets.aeso.ca/ets_web/ip/Market/Reports/CSDReportServlet" },
  // Ireland loader emits both children from one EirGrid/SONI DD half-hourly
  // workbook fetch. The all-island half-hourly DD feed is split 58/42 using
  // the 2024 annual ROI/NI anchor.
  { id: "ireland-republic", name: "Ireland (Republic)",  country: "IRL", lat: 53.3, lon:   -7.8, tier: "live", kind: "wind",  source: "EirGrid/SONI DD half-hourly workbook (ROI 58% of all-island DD)", sourceUrl: "https://www.eirgrid.ie/grid/system-and-renewable-data-reports" },
  { id: "northern-ireland", name: "Northern Ireland",    country: "GBR", lat: 54.65, lon:  -6.65, tier: "live", kind: "wind",  source: "EirGrid/SONI DD half-hourly workbook (NI 42% of all-island DD)", sourceUrl: "https://www.eirgrid.ie/grid/system-and-renewable-data-reports" },
  { id: "peru-hydro",       name: "Peru Hydro",       country: "PER", lat: -12.5, lon: -75.0, tier: "live", kind: "hydro", source: "COES-SINAC live hydro generation × 2% curtailment calibration (vertimiento anchor ~0.8 TWh/yr)", sourceUrl: "https://www.coes.org.pe/Portal/portalinformacion/generacion" },
  { id: "peru-solar",       name: "Peru Solar",       country: "PER", lat: -14.0, lon: -71.5, tier: "live", kind: "solar", source: "COES-SINAC live solar generation × 2% curtailment calibration (vertimiento anchor ~0.8 TWh/yr)", sourceUrl: "https://www.coes.org.pe/Portal/portalinformacion/generacion" },
  { id: "peru-wind",        name: "Peru Wind",        country: "PER", lat: -17.0, lon: -72.0, tier: "live", kind: "wind",  source: "COES-SINAC live wind generation × 2% curtailment calibration (vertimiento anchor ~0.8 TWh/yr)", sourceUrl: "https://www.coes.org.pe/Portal/portalinformacion/generacion" },
  { id: "south-africa-solar", name: "South Africa Solar", country: "ZAF", lat: -29.0, lon:  22.0, tier: "live", kind: "solar", source: "Eskom Data Portal total hourly renewable generation (PV+CSP columns × 12% curtailment)", sourceUrl: "https://www.eskom.co.za/dataportal/renewables-performance/total-hourly-renewable-generation/" },
  { id: "south-africa-wind",  name: "South Africa Wind",  country: "ZAF", lat: -33.5, lon:  25.5, tier: "live", kind: "wind", source: "Eskom Data Portal total hourly renewable generation (Wind column × 12% curtailment)", sourceUrl: "https://www.eskom.co.za/dataportal/renewables-performance/total-hourly-renewable-generation/" },
  { id: "new-zealand",      name: "New Zealand",     country: "NZL", lat: -40.9, lon: 172.0, tier: "live", kind: "mixed", source: "EMI wind+solar+geo", sourceUrl: "https://www.emi.ea.govt.nz/Wholesale/Datasets/Generation/Generation_MD" },
  { id: "atacama",          name: "Atacama",         country: "CHL", lat: -24.5, lon: -69.2, tier: "live",   kind: "solar", source: "CEN Chile XLSX", sourceUrl: "https://www.coordinador.cl/operacion/documentos/reducciones-de-generacion-renovable/" },
  { id: "chile-wind",       name: "Chile Wind",      country: "CHL", lat: -38.5, lon: -72.5, tier: "live",   kind: "wind",  source: "CEN Chile monthly XLSX wind reductions", sourceUrl: "https://www.coordinador.cl/operacion/documentos/reducciones-de-generacion-renovable/" },
  // Tier 2 - static fallback regions
  { id: "sichuan",          name: "Sichuan",         country: "CHN", lat: 30.6, lon:  102.8, tier: "static", kind: "hydro", source: "NEA 2024 / Sichuan hydro-spill proxy", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "xinjiang",         name: "Xinjiang",        country: "CHN", lat: 41.5, lon:   85.0, tier: "static", kind: "solar", source: "NEA 2024 / Huaon-NBS generation", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "inner-mongolia",   name: "Inner Mongolia",  country: "CHN", lat: 43.0, lon:  112.0, tier: "static", kind: "wind",  source: "NEA 2024 / Huaon-NBS generation", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "gansu",            name: "Gansu",           country: "CHN", lat: 39.0, lon:   97.0, tier: "static", kind: "mixed", source: "NEA 2024 / Gansu MIIT generation", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "qinghai",          name: "Qinghai",         country: "CHN", lat: 36.0, lon:   98.0, tier: "static", kind: "solar", source: "NEA 2024 / Huaon-NBS generation", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "ningxia",          name: "Ningxia",         country: "CHN", lat: 37.5, lon:  106.0, tier: "static", kind: "mixed", source: "NEA 2024 / Huaon-NBS generation", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "yunnan",           name: "Yunnan",          country: "CHN", lat: 25.0, lon:  101.5, tier: "static", kind: "hydro", source: "NEA 2024 / Yunnan statistics", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "tibet",            name: "Tibet (Xizang)",  country: "CHN", lat: 30.0, lon:   90.0, tier: "static", kind: "hydro", source: "NEA 2024 / Huaon-NBS generation", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-shandong",   name: "Shandong",        country: "CHN", lat: 36.5, lon:  118.5, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~4.5 TWh/yr (96.3% PV utilisation)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-guangdong",  name: "Guangdong",       country: "CHN", lat: 23.5, lon:  113.0, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — CSG-grid mixed wind+solar curtailment ~3.2 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-jiangsu",    name: "Jiangsu",         country: "CHN", lat: 32.5, lon:  119.5, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — offshore wind + solar curtailment ~2.8 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-anhui",      name: "Anhui",           country: "CHN", lat: 31.5, lon:  117.5, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~2.1 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-hunan",      name: "Hunan",           country: "CHN", lat: 27.5, lon:  111.5, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — mixed wind+solar+hydro curtailment ~1.9 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-liaoning",   name: "Liaoning",        country: "CHN", lat: 41.5, lon:  122.5, tier: "static", kind: "wind",   source: "NEA 2024 provincial RE monitoring bulletin — wind curtailment ~1.6 TWh/yr (northeast grid transmission constraint)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-hebei",        name: "Hebei",        country: "CHN", lat: 39.0, lon: 116.5, tier: "static", kind: "wind", source: "NEA 2024 provincial RE monitoring bulletin — wind curtailment ~2 TWh/yr (north China wind corridor, Zhangjiakou transmission bottleneck)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-heilongjiang", name: "Heilongjiang", country: "CHN", lat: 47.0, lon: 128.5, tier: "static", kind: "wind", source: "NEA 2024 provincial RE monitoring bulletin — wind curtailment ~1.5 TWh/yr (northeast grid; Daqing-area wind build-out)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-jilin",        name: "Jilin",        country: "CHN", lat: 43.8, lon: 126.5, tier: "static", kind: "wind", source: "NEA 2024 provincial RE monitoring bulletin — wind curtailment ~1 TWh/yr (northeast grid; Baicheng wind corridor)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-hubei",      name: "Hubei",           country: "CHN", lat: 30.5, lon:  113.0, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — mixed solar+wind+hydro curtailment ~1.5 TWh/yr (Three Gorges basin; missed RE consumption target)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-shanxi",     name: "Shanxi",          country: "CHN", lat: 37.5, lon:  112.5, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — mixed wind+solar curtailment ~1.4 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-shaanxi",    name: "Shaanxi",         country: "CHN", lat: 35.5, lon:  108.5, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~1.1 TWh/yr (Guanzhong basin PV)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-zhejiang",   name: "Zhejiang",        country: "CHN", lat: 29.0, lon:  120.0, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — coastal mixed wind+solar curtailment ~0.8 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-henan",      name: "Henan",           country: "CHN", lat: 34.0, lon:  113.5, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~0.7 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-fujian",     name: "Fujian",          country: "CHN", lat: 26.0, lon:  118.0, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — coastal mixed wind+solar curtailment ~0.6 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-jiangxi",    name: "Jiangxi",         country: "CHN", lat: 28.5, lon:  115.5, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~0.4 TWh/yr (99.0% PV utilisation, 25+ GW distributed solar)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-beijing",    name: "Beijing",         country: "CHN", lat: 39.9, lon:  116.4, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~0.28 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-guizhou",    name: "Guizhou",         country: "CHN", lat: 26.5, lon:  106.5, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — mixed solar+hydro curtailment ~0.25 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-chongqing",  name: "Chongqing",       country: "CHN", lat: 29.6, lon:  106.6, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — mixed hydro+solar curtailment ~0.22 TWh/yr (Yangtze basin)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-tianjin",    name: "Tianjin",         country: "CHN", lat: 39.1, lon:  117.3, tier: "static", kind: "mixed",  source: "NEA 2024 provincial RE monitoring bulletin — mixed wind+solar curtailment ~0.16 TWh/yr", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-hainan",     name: "Hainan",          country: "CHN", lat: 19.2, lon:  109.7, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~0.01 TWh/yr (99.8% PV utilisation; near-zero)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "china-shanghai",   name: "Shanghai",        country: "CHN", lat: 31.2, lon:  121.5, tier: "static", kind: "solar",  source: "NEA 2024 provincial RE monitoring bulletin — solar curtailment ~0.01 TWh/yr (100% PV utilisation; effectively zero, placeholder)", sourceUrl: "https://www.nea.gov.cn/20251113/cc1fb0298a2944f8bd5441f67c9be9b3/c.html" },
  { id: "iceland",          name: "Iceland",         country: "ISL", lat: 64.9, lon:  -19.0, tier: "static", kind: "hydro", source: "Published", sourceUrl: "https://orkustofnun.is/" },
  { id: "argentina",        name: "Argentina",       country: "ARG", lat: -43.0, lon: -65.0, tier: "static", kind: "wind",  source: "CAMMESA / IRENA fallback", sourceUrl: "https://cammesaweb.cammesa.com/" },
  { id: "uruguay",          name: "Uruguay",         country: "URY", lat: -33.5, lon: -56.0, tier: "live", kind: "wind",  source: "ADME hourly Restricciones Operativas workbook", sourceUrl: "https://www.adme.com.uy/panelControl/ro_excel.php" },
  { id: "paraguay",         name: "Paraguay",        country: "PRY", lat: -25.4, lon: -54.6, tier: "static", kind: "hydro", source: "Itaipu fallback", sourceUrl: "https://www.itaipu.gov.py/" },
  // T1b live-domestic-anchored: XM SinerGox API (geoblocked from non-Colombian IPs) with
  // committed daily CSV relay as fallback. ENSO-driven range 0.53–13.12 TWh/yr anchors
  // the ±50% T1b envelope rather than statistical 2σ. See docs/validation/colombia.md.
  { id: "colombia",         name: "Colombia",        country: "COL", lat: 4.6, lon: -74.1, tier: "live-domestic-anchored", kind: "hydro", source: "XM SinerGox API (servapibi.xm.com.co/daily, POST MetricId=VertEner Entity=Sistema) — direct live path tried first; committed CSV relay fallback if geoblocked. Trailing-365-day annualised total. 5-yr baseline 7.53 TWh/yr (range 0.53–13.12 TWh/yr ENSO-driven). Bimodal hydro-seasonal shape (Apr–Jun + Oct–Nov peaks). T1b, ±50% envelope.", sourceUrl: "https://servapibi.xm.com.co/daily" },
  { id: "mexico",           name: "Mexico",          country: "MEX", lat: 25.0, lon: -103.0, tier: "static", kind: "solar", source: "SENER PRODESEN 2024-2038 + CRE confiabilidad reports — ~1.2 TWh/yr solar+wind curtailment from northern-grid transmission saturation (Sonora/Chihuahua/Coahuila/Oaxaca). Excludes hydro vertimientos. Gemini-3.1 research wave 2 (2026-04-30).", sourceUrl: "https://www.gob.mx/sener/documentos/programa-de-desarrollo-del-sistema-electrico-nacional-2024-2038" },
  { id: "japan-chubu",      name: "Chubu (Japan)",   country: "JPN", lat: 35.18, lon: 136.91, tier: "live",   kind: "solar", source: "Chubu Electric Power Grid juyo CSV × 1% calibrated curtailment (OCCTO FY2024 Chubu anchor: ~0.05 TWh/yr)", sourceUrl: "https://denki-yoho.chuden.jp/" },
  { id: "japan-chugoku",   name: "Chugoku (Japan)", country: "JPN", lat: 34.39, lon: 132.45, tier: "live",   kind: "solar", source: "Chugoku Electric juyo CSV (5-min solar) × 6% calibrated curtailment (OCCTO FY2024 Chugoku anchor: ~0.40 TWh/yr)", sourceUrl: "https://www.energia.co.jp/nw/jukyuu/sys/" },
  { id: "japan-hokkaido",  name: "Hokkaido (Japan)", country: "JPN", lat: 43.06, lon: 141.35, tier: "live",  kind: "solar", source: "Hokkaido Electric juyo CSV (5-min solar) × 5% calibrated curtailment (OCCTO FY2024 Hokkaido anchor: ~0.10 TWh/yr)", sourceUrl: "https://denkiyoho.hepco.co.jp/" },
  { id: "japan-hokuriku",  name: "Hokuriku (Japan)", country: "JPN", lat: 36.57, lon: 136.63, tier: "live",  kind: "solar", source: "Hokuriku Electric juyo CSV (5-min solar) × 1% calibrated curtailment (OCCTO FY2024 Hokuriku anchor: ~0.02 TWh/yr)", sourceUrl: "https://www.rikuden.co.jp/nw/denki-yoho/" },
  { id: "japan-kansai",    name: "Kansai (Japan)",  country: "JPN", lat: 34.69, lon: 135.50, tier: "live",   kind: "solar", source: "Kansai Electric T&D juyo CSV (5-min solar, live) × 1% calibrated curtailment (OCCTO FY2024 Kansai anchor: ~0.05 TWh/yr)", sourceUrl: "https://www.kansai-td.co.jp/" },
  { id: "japan-kyushu",    name: "Kyushu (Japan)",  country: "JPN", lat: 33.0, lon:  131.0, tier: "live",    kind: "solar", source: "Kyushu Electric area-demand CSV (5-min solar) × 10% calibrated curtailment (OCCTO FY2024 Kyushu anchor: ~1.7 TWh/yr)", sourceUrl: "https://www.kyuden.co.jp/td_power_usages/pc.html" },
  { id: "japan-okinawa",   name: "Okinawa (Japan)", country: "JPN", lat: 26.21, lon: 127.68, tier: "live",   kind: "solar", source: "Okinawa Electric juyo CSV × 2% calibrated curtailment (OCCTO FY2024 Okinawa anchor: ~0.04 TWh/yr)", sourceUrl: "https://www.okiden.co.jp/" },
  { id: "japan-shikoku",   name: "Shikoku (Japan)", country: "JPN", lat: 34.34, lon: 134.04, tier: "live",   kind: "solar", source: "Shikoku Electric T&D juyo CSV × 7% calibrated curtailment (OCCTO FY2024 Shikoku anchor: ~0.30 TWh/yr)", sourceUrl: "https://www.yonden.co.jp/nw/" },
  { id: "japan-tepco",     name: "TEPCO (Japan)",   country: "JPN", lat: 35.68, lon: 139.69, tier: "live",   kind: "solar", source: "TEPCO Power Grid juyo CSV × 1% calibrated curtailment (OCCTO FY2024 TEPCO anchor: ~0.05 TWh/yr)", sourceUrl: "https://www.tepco.co.jp/forecast/" },
  { id: "japan-tohoku",    name: "Tohoku (Japan)",  country: "JPN", lat: 38.3, lon: 140.5,  tier: "live",    kind: "solar", source: "Tohoku Electric area supply/demand CSV — direct 太陽光出力制御量+風力出力制御量 columns (MW, 30-min). Solar-dominant (>95% of measured curtailment). FY2023 OCCTO anchor: 0.13 TWh; rising ~1.5-2 TWh/yr.", sourceUrl: "https://setsuden.nw.tohoku-epco.co.jp/common/demand/realtime_jukyu/" },
  { id: "vietnam",          name: "Vietnam",         country: "VNM", lat: 11.5, lon:  108.8, tier: "static", kind: "solar", source: "EVN fallback", sourceUrl: "https://www.evn.com.vn/" },
  { id: "thailand",         name: "Thailand",        country: "THA", lat: 14.5, lon:  101.0, tier: "static", kind: "solar", source: "EGAT fallback", sourceUrl: "https://www.egat.co.th/en/" },
  { id: "india-rajasthan",  name: "Rajasthan",       country: "IND", lat: 26.5, lon:   73.0, tier: "static", kind: "solar", source: "RRVPNL SLDC (Rajasthan State Load Despatch Centre) — RE curtailment downloads at sldc.rajasthan.gov.in. Geoblocked from non-Indian IP ranges; loader currently emits T3-modelled typical-shape calibrated to Ember India 2025 (~3.5 TWh/yr solar curtailment). Will be promoted to T1a-live-tso when the India-egress relay activates the live parse.", sourceUrl: "https://sldc.rajasthan.gov.in/" },
  // india-south (static) and india-west (static) replaced by state-level T1a loaders in India W2.
  { id: "india-gujarat",    name: "Gujarat",         country: "IND", lat: 23.0, lon:   70.0, tier: "static", kind: "solar", source: "GSLDC (Gujarat State Load Despatch Centre / GETCO) — RE curtailment reports at sldc.gujarat.gov.in. Geoblocked from non-Indian IP ranges; loader currently emits T3-modelled typical-shape calibrated to POSOCO/Ember India 2024 (~1.0 TWh/yr solar curtailment). Will be promoted to T1a-live-tso when the India-egress relay activates the live parse.", sourceUrl: "https://sldc.gujarat.gov.in/" },
  { id: "india-tamil-nadu", name: "Tamil Nadu",      country: "IND", lat: 10.5, lon:   77.5, tier: "static", kind: "wind",  source: "TNSLDC (Tamil Nadu State Load Despatch Centre / TANTRANSCO) — RE curtailment and system operation reports at tnsldc.com. Geoblocked from non-Indian IP ranges; loader currently emits T3-modelled typical-shape calibrated to POSOCO South Region 2024 (~1.0 TWh/yr wind curtailment; India's largest wind state). Will be promoted to T1a-live-tso when the India-egress relay activates the live parse.", sourceUrl: "https://tnsldc.com/" },
  { id: "india-karnataka",      name: "Karnataka",       country: "IND", lat: 14.5, lon:   76.0, tier: "static", kind: "solar", source: "KSLDC (Karnataka State Load Despatch Centre) — real-time dashboard and curtailment PDFs at ksldc.in. Probed successfully in April 2026 coverage audit; parser not yet implemented. Loader currently emits T3-modelled typical-shape calibrated to POSOCO South Region 2024 (~0.5 TWh/yr Karnataka solar curtailment). Will be promoted to T1a-live-tso when the parser ships.", sourceUrl: "https://ksldc.in/" },
  { id: "india-andhra-pradesh", name: "Andhra Pradesh",  country: "IND", lat: 15.9, lon:   79.7, tier: "static", kind: "solar", source: "APTRANSCO / APSLDC (Andhra Pradesh Transmission Corporation Ltd / State Load Despatch Centre) — RE curtailment data at apsldc.in. Geoblocked from non-Indian IP ranges; loader currently emits T3-modelled typical-shape calibrated to POSOCO Southern Region 2024 (~0.4 TWh/yr solar curtailment). Will be promoted to T1a-live-tso when the India-egress relay activates the live parse.", sourceUrl: "https://apsldc.in/" },
  { id: "india-maharashtra",    name: "Maharashtra",     country: "IND", lat: 19.7, lon:   75.7, tier: "static", kind: "mixed", source: "MSLDC (Maharashtra State Load Despatch Centre / MSEDCL) — RE curtailment and system data at msldc.mahavedha.com. Geoblocked from non-Indian IP ranges; loader currently emits T3-modelled typical-shape calibrated to POSOCO Western Region 2024 (~0.3 TWh/yr mixed solar+wind curtailment; Solapur solar + Satara/Dhule wind corridor). Will be promoted to T1a-live-tso when the India-egress relay activates the live parse.", sourceUrl: "https://msldc.mahavedha.com/" },
  { id: "india-east",       name: "India East",      country: "IND", lat: 22.0, lon:   87.0, tier: "static", kind: "solar", source: "ERLDC fallback", sourceUrl: "https://erldc.in/" },
  { id: "cyprus",           name: "Cyprus",          country: "CYP", lat: 35.0, lon:   33.0, tier: "static", kind: "solar", source: "TSOC fallback", sourceUrl: "https://tsoc.org.cy/" },
  { id: "ethiopia",         name: "Ethiopia",        country: "ETH", lat: 10.5, lon:   37.0, tier: "static", kind: "hydro", source: "EEP fallback", sourceUrl: "https://www.eep.com.et/" },
  { id: "kenya",            name: "Kenya",           country: "KEN", lat: -0.9, lon:   36.3, tier: "static", kind: "hydro", source: "EPRA 2025 (geothermal overnight venting)", sourceUrl: "https://www.epra.go.ke/publications/" },
  { id: "egypt",            name: "Egypt",           country: "EGY", lat: 24.5, lon:   32.7, tier: "static", kind: "solar", source: "NREA / Benban frequency disconnections", sourceUrl: "https://nrea.gov.eg/" },
  { id: "morocco",          name: "Morocco",         country: "MAR", lat: 31.5, lon:   -6.0, tier: "static", kind: "mixed", source: "ANRE 2024 (south-north transmission)", sourceUrl: "http://www.anre.ma/" },
  { id: "namibia",          name: "Namibia",         country: "NAM", lat: -22.0, lon:  17.0, tier: "static", kind: "solar", source: "NamPower ISB 2025", sourceUrl: "https://www.nampower.com.na/" },
  { id: "kazakhstan",       name: "Kazakhstan",      country: "KAZ", lat: 48.0, lon:   66.9, tier: "static", kind: "wind",  source: "KEGOC fallback", sourceUrl: "https://www.kegoc.kz/" },
  { id: "mongolia",         name: "Mongolia",        country: "MNG", lat: 47.0, lon:  105.0, tier: "static", kind: "wind",  source: "NPTG fallback", sourceUrl: "https://nptg.mn/" },
  // Phase 2 IRENA T3 anchors (2026-05-04).
  // Albania: Karavasta 140 MW + Spitalla 100 MW = ~240 MW solar; wind negligible.
  // Georgia: ~100 MW solar+wind combined; hydro-dominant.
  // Armenia: solar growing post-2020, ~180 MW; wind negligible.
  // Azerbaijan: both solar and wind in operation post-2023, ~200 MW each.
  // Uzbekistan: major utility-scale solar build-out post-2021, ~1-2 GW solar.
  // Sri Lanka: 450 MW solar + 300 MW wind per CEB/IRENA.
  // Sudan: utility solar deployed, ongoing conflict — data uncertainty acknowledged.
  // Venezuela: Paraguaná wind farm legacy (~100 MW); grid distress limits VRE output.
  // Bhutan: hydro-only, no dispatch-driven VRE; skipped per methodology.
  // Kyrgyzstan: hydro-dominant; VRE <50 MW threshold; skipped per methodology.
  // Tajikistan: hydro-dominant; VRE <50 MW threshold; skipped per methodology.
  { id: "albania",           name: "Albania",          country: "ALB", lat: 41.33, lon:   19.82, tier: "static", kind: "solar",  source: "IRENA RE Statistics 2024 (~240 MW solar capacity: Karavasta 140 MW + Spitalla 100 MW); wind negligible; modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "georgia",           name: "Georgia",          country: "GEO", lat: 41.69, lon:   44.79, tier: "static", kind: "mixed", source: "IRENA RE Statistics 2024 (~100 MW solar+wind combined, ~1.8 GW hydro); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "armenia",           name: "Armenia",          country: "ARM", lat: 40.18, lon:   44.51, tier: "static", kind: "solar", source: "IRENA RE Statistics 2024 (~180 MW solar capacity, growing post-2020); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "azerbaijan",       name: "Azerbaijan",       country: "AZE", lat: 40.41, lon:   49.87, tier: "static", kind: "mixed", source: "IRENA RE Statistics 2024 (~200 MW solar + ~200 MW wind in operation post-2023); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "uzbekistan",       name: "Uzbekistan",       country: "UZB", lat: 41.30, lon:   69.28, tier: "static", kind: "solar", source: "IRENA RE Statistics 2024 (~1-2 GW utility-scale solar build-out post-2021); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "sri-lanka",        name: "Sri Lanka",        country: "LKA", lat:  7.87, lon:   80.77, tier: "static", kind: "mixed", source: "IRENA RE Statistics 2024 (~450 MW solar + ~300 MW wind operational); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "sudan",            name: "Sudan",            country: "SDN", lat:  15.50, lon:   32.56, tier: "static", kind: "solar", source: "IRENA RE Statistics 2024 (utility solar deployed; ongoing conflict introduces data uncertainty); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "venezuela",        name: "Venezuela",        country: "VEN", lat:  10.49, lon:  -66.90, tier: "static", kind: "wind",  source: "IRENA RE Statistics 2024 (Paraguaná wind farm ~100 MW; grid distress limits VRE output); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "laos",             name: "Laos",             country: "LAO", lat:  17.98, lon:  102.63, tier: "static", kind: "solar", source: "IRENA RE Statistics 2024 (hydro-export economy; some utility solar deployed); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "cambodia",         name: "Cambodia",         country: "KHM", lat:  11.56, lon:  104.92, tier: "static", kind: "solar", source: "IRENA RE Statistics 2024 (~470 MW solar 2024, rapid solar growth); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "myanmar",          name: "Myanmar",          country: "MMR", lat:  19.75, lon:   96.10, tier: "static", kind: "solar", source: "IRENA RE Statistics 2024 (some utility solar; post-coup data validity uncertainty); modelled curtailment ~2% per regional default", sourceUrl: "https://www.irena.org/Data/Energy-Profiles" },
  { id: "honduras",         name: "Honduras",        country: "HND", lat: 15.2, lon:  -86.2, tier: "static", kind: "solar", source: "ODS Honduras fallback", sourceUrl: "https://ods.org.hn/" },
  { id: "jeju",             name: "Jeju (S. Korea)", country: "KOR", lat: 33.49, lon: 126.50, tier: "static", kind: "wind",  source: "KPX Jeju fallback", sourceUrl: "https://www.kpx.or.kr/" },
  { id: "wa-swis-solar", name: "Western Australia Solar (SWIS)", country: "AUS", lat: -28.8, lon: 114.6, tier: "live", kind: "solar", source: "AEMO WEM Facility SCADA (solar DUIDs)", sourceUrl: "https://data.wa.aemo.com.au/" },
  { id: "wa-swis-wind",  name: "Western Australia Wind (SWIS)", country: "AUS", lat: -35.0, lon: 117.9, tier: "live", kind: "wind", source: "AEMO WEM Facility SCADA (wind DUIDs)", sourceUrl: "https://data.wa.aemo.com.au/" },
  { id: "nt-pilbara",       name: "NT & Pilbara",    country: "AUS", lat: -22.0, lon: 118.0, tier: "static", kind: "solar", source: "Horizon/Pilbara fallback", sourceUrl: "https://www.horizonpower.com.au/" },
  { id: "indonesia",        name: "Indonesia",       country: "IDN", lat:  -7.0, lon: 110.0, tier: "static", kind: "solar", source: "PLN fallback", sourceUrl: "https://web.pln.co.id/" },
  { id: "malaysia",         name: "Malaysia",        country: "MYS", lat:   3.5, lon: 102.0, tier: "static", kind: "solar", source: "IRENA Malaysia 2024 + Suruhanjaya Tenaga (ST) 2024 anchor (~0.15 TWh/yr provisional). Gemini-3.1 research wave 2026-04-29: SEDA / ST policy classifies systemic renewable curtailment as a 'rising risk' for Peninsular Malaysia but reports current operations as stable; no published annual curtailment TWh figure exists yet. Live promotion attempt reverted (GSO real-time solar feed is generation-only, not curtailment). Held at T3 pending publication of a real curtailment figure.", sourceUrl: "https://www.gso.org.my/" },
  { id: "philippines-solar", name: "Philippines Solar", country: "PHL", lat:  14.6, lon: 121.0, tier: "static", kind: "solar", source: "IRENA Philippines RE Statistics 2024 anchor; IEMOP RTD endpoint exposes current-day dispatch schedules, not curtailed-energy. The 2% rate previously applied was an invented placeholder with no published source. Held at T3 until IEMOP/WESM publishes a citable curtailment rate.", sourceUrl: "https://www.iemop.ph/market-data/rtd-prices-and-schedules/" },
  { id: "philippines-wind",  name: "Philippines Wind",  country: "PHL", lat:  14.6, lon: 121.0, tier: "static", kind: "wind",  source: "IRENA Philippines RE Statistics 2024 anchor; IEMOP RTD endpoint exposes current-day dispatch schedules, not curtailed-energy. The 2% rate previously applied was an invented placeholder with no published source. Held at T3 until IEMOP/WESM publishes a citable curtailment rate.", sourceUrl: "https://www.iemop.ph/market-data/rtd-prices-and-schedules/" },
  { id: "south-korea",      name: "South Korea (mainland)", country: "KOR", lat: 35.5, lon: 127.0, tier: "static", kind: "solar", source: "KPX fallback", sourceUrl: "https://www.kpx.or.kr/eng/" },
  { id: "russia-mainland",  name: "Russia (European grid)", country: "RUS", lat: 55.8, lon:  38.0, tier: "static", kind: "hydro", source: "SO UES fallback", sourceUrl: "https://www.so-ups.ru/" },
  { id: "taiwan",           name: "Taiwan",          country: "TWN", lat:  23.9, lon: 120.4, tier: "static", kind: "mixed", source: "TAIPOWER + TREC + IRENA 2024 anchor. Live promotion attempt 2026-04-29 reverted: TAIPOWER `genary.json` exposes current-unit output and instantaneous renewable percentages, not a 30-day public curtailment archive or single published curtailment rate. Held at T3 pending the archive/rate chain.", sourceUrl: "https://www.taipower.com.tw/d006/loadGraph/loadGraph/genshx_.html" },
  { id: "jordan",           name: "Jordan",          country: "JOR", lat:  30.8, lon:  35.8, tier: "static", kind: "solar", source: "NEPCO fallback", sourceUrl: "https://www.nepco.com.jo/" },
  { id: "saudi-solar",      name: "Saudi Arabia (solar)", country: "SAU", lat: 25.5, lon: 46.5, tier: "static", kind: "solar", source: "GASTAT 2024 (5.2% curtailment ~0.8 TWh; grid constraints vs Sudair/Sakaka/NEOM scale-up). Gemini-3.1 research wave 4 (2026-04-30).", sourceUrl: "https://www.stats.gov.sa/" },
  { id: "uae",              name: "UAE",             country: "ARE", lat:  24.5, lon:  54.4, tier: "static", kind: "solar", source: "DEWA/EWEC fallback", sourceUrl: "https://www.dewa.gov.ae/" },
  { id: "oman",             name: "Oman",            country: "OMN", lat:  23.5, lon:  57.5, tier: "static", kind: "solar", source: "OPWP fallback", sourceUrl: "https://www.omanpwp.om/" },
  { id: "israel",           name: "Israel",          country: "ISR", lat:  30.8, lon:  34.8, tier: "static", kind: "solar", source: "Noga fallback", sourceUrl: "https://www.noga-iso.co.il/" },
  { id: "pakistan",         name: "Pakistan",        country: "PAK", lat:  28.0, lon:  67.5, tier: "static", kind: "mixed", source: "NEPRA State of Industry Report 2024: Non-Project Missed Volume (NPMV) for wind power = 1,337 GWh FY2023-24 = PKR 39.5 billion in transmission-constrained dispatch-down compensation (Jhimpir/Gharo/Thatta wind corridor, Sindh). Solar curtailment exists but not separately quantified. Gemini-3.1 research wave 2 (2026-04-30).", sourceUrl: "https://nepra.org.pk/publications/State%20of%20Industry%20Reports/State%20of%20Industry%20Report%202024.pdf" },
  { id: "nepal",            name: "Nepal",           country: "NPL", lat:  28.0, lon:  84.0, tier: "static", kind: "hydro", source: "World Bank Nepal Development Update 2024 — estimated >0.5 TWh/yr renewable energy spillage from monsoon-season run-of-river overgeneration vs transmission bottlenecks and limited India-export capacity. NEA confirms during FY2023/24. Same modelling treatment as Ethiopia/Iceland/Colombia hydro spillage. Himalayan summer-monsoon shape (peak Jul-Sep). Gemini-3.1 research wave 4 (2026-04-30, reliability 5/5).", sourceUrl: "https://www.worldbank.org/en/country/nepal/publication/nepal-development-update" },
  { id: "iran",             name: "Iran",            country: "IRN", lat:  33.0, lon:  52.0, tier: "static", kind: "solar", source: "TAVANIR fallback", sourceUrl: "https://www.tavanir.org.ir/" },
  { id: "iraq-mainland",    name: "Iraq (non-flare)", country: "IRQ", lat: 34.0, lon: 43.5, tier: "static", kind: "solar", source: "Ministry of Electricity fallback", sourceUrl: "https://moelc.gov.iq/" },
  { id: "kurdistan",        name: "Kurdistan (KRG)", country: "IRQ", lat:  36.5, lon:  44.0, tier: "static", kind: "solar", source: "KRG Ministry fallback", sourceUrl: "https://gov.krd/moel-en/" },
  { id: "bangladesh",       name: "Bangladesh",      country: "BGD", lat:  24.0, lon:  90.0, tier: "static", kind: "solar", source: "BPDB fallback", sourceUrl: "https://bpdb.gov.bd/" },
  { id: "brazil-mg-wind",   name: "Minas Gerais Wind", country: "BRA", lat: -18.0, lon: -44.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-mg-solar",  name: "Minas Gerais Solar", country: "BRA", lat: -17.8, lon: -43.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-sp-wind",   name: "Sao Paulo Wind", country: "BRA", lat: -22.5, lon: -48.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-sp-solar",  name: "Sao Paulo Solar", country: "BRA", lat: -22.3, lon: -47.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-mt-wind",   name: "Mato Grosso Wind", country: "BRA", lat: -13.0, lon: -56.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-mt-solar",  name: "Mato Grosso Solar", country: "BRA", lat: -12.8, lon: -55.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-go-wind",   name: "Goias Wind", country: "BRA", lat: -16.0, lon: -49.7, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-go-solar",  name: "Goias Solar", country: "BRA", lat: -15.8, lon: -49.3, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-pr-wind",   name: "Parana Wind", country: "BRA", lat: -25.0, lon: -52.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-pr-solar",  name: "Parana Solar", country: "BRA", lat: -24.8, lon: -51.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-rs-wind",   name: "Rio Grande do Sul Wind", country: "BRA", lat: -30.0, lon: -53.2, tier: "live", kind: "wind",  source: "ONS wind constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "brazil-rs-solar",  name: "Rio Grande do Sul Solar", country: "BRA", lat: -29.8, lon: -52.8, tier: "live", kind: "solar", source: "ONS solar constrained-off", sourceUrl: "https://www.ons.org.br/" },
  { id: "british-columbia", name: "British Columbia", country: "CAN", lat: 54.0, lon: -124.0, tier: "static", kind: "hydro", source: "BC Hydro fallback", sourceUrl: "https://www.bchydro.com/" },
  { id: "quebec",           name: "Quebec",          country: "CAN", lat:  52.0, lon: -72.0, tier: "static", kind: "hydro", source: "Hydro-Quebec fallback", sourceUrl: "https://www.hydroquebec.com/" },
  { id: "manitoba",         name: "Manitoba",        country: "CAN", lat:  54.0, lon: -98.0, tier: "static", kind: "mixed", source: "Manitoba Hydro fallback", sourceUrl: "https://www.hydro.mb.ca/" },
  { id: "saskatchewan",     name: "Saskatchewan",    country: "CAN", lat:  52.0, lon: -106.0, tier: "static", kind: "wind",  source: "SaskPower fallback", sourceUrl: "https://www.saskpower.com/" },
  // v0.6 — Codex global-coverage-audit 2026-04-24 additions.
  // Hawaiian Electric publishes a per-island curtailment metric (RSWG
  // monthly + annual historical workbook). TWh anchors are provisional
  // pending workbook extraction; see docs/research/2026-04-24-global-coverage-audit.md.
  { id: "hawaii-oahu",      name: "Hawaii (Oahu)",       country: "USA", lat:  21.46, lon: -158.00, tier: "static", kind: "solar", source: "Hawaiian Electric RSWG monthly reports (Oahu: ~30% renewable share 2024, provisional)", sourceUrl: "https://www.hawaiianelectric.com/about-us/performance-scorecards-and-metrics/renewable-energy" },
  { id: "hawaii-maui",      name: "Hawaii (Maui)",       country: "USA", lat:  20.80, lon: -156.33, tier: "static", kind: "solar", source: "Hawaiian Electric RSWG monthly reports (Maui island system)", sourceUrl: "https://www.hawaiianelectric.com/about-us/performance-scorecards-and-metrics/renewable-energy" },
  { id: "hawaii-island",    name: "Hawaii (Big Island)", country: "USA", lat:  19.60, lon: -155.50, tier: "static", kind: "mixed", source: "Hawaiian Electric RSWG (Hawaii Island: 58.7% renewable share 2024)", sourceUrl: "https://www.hawaiianelectric.com/about-us/performance-scorecards-and-metrics/renewable-energy" },
  { id: "florida",          name: "Florida",        country: "USA", lat:  27.6,  lon:  -81.2, tier: "static", kind: "solar", source: "EIA FLA solar generation exists, but no published curtailment rate from FRCC/FPL. 0.5 TWh/yr provisional anchor — requires FRCC market monitor or FPL IRP 2024 published curtailment figure to move to T1.", sourceUrl: "https://www.eia.gov/opendata/browser/electricity/rto/fuel-type-data" },
  // Austria — APG confirms 2024 redispatch events involving renewable
  // curtailment; no public annual TWh anchor. Held as a provisional
  // static until an ENTSO-E A75 extraction pass is wired.
  { id: "austria",          name: "Austria",             country: "AUT", lat:  47.60, lon:   14.30, tier: "static", kind: "mixed", source: "APG Strombilanz 2024 + ENTSO-E redispatch A75 (provisional anchor)", sourceUrl: "https://www.apg.at/en/news-press/apg-strombilanz-2024-oesterreich-erstmals-wieder-exportland/" },
  // Russia / Kola Peninsula — SO UPS 2024 monthly DPM VIE reports cite
  // explicit wind output limits (84 MW Sep 2024, 77 MW Nov 2024). Treated
  // as a narrow source upgrade to russia-mainland for the one Russian
  // sub-region with public dispatch-curtailment evidence.
  { id: "russia-murmansk-wind", name: "Russia (Murmansk)", country: "RUS", lat: 68.90, lon:  33.10, tier: "static", kind: "wind",  source: "SO UPS 2024 monthly DPM VIE reports (Kola Peninsula wind dispatch limits)", sourceUrl: "https://www.so-ups.ru/functioning/markets/surveys/renewable/2024/" },
  // Phase-2.7 Pattern-D Latin-America bulk-add (2026-04-27, codex/phase-27-latam-pattern-d).
  // Sixteen Caribbean + Central American + small South American grids tagged
  // `recommended_action: introduce-as-T3` in the audit
  // `data/coverage-audit/2026-04-26-latin-america.csv`. Each row is a sub-1 TWh
  // anchor, all T3-modelled (±40% envelope) per the canonical Pattern-D entry
  // pattern documented at `docs/proposals/2026-04-27-phase-2-7-pattern-d-dispatch.md` §3.
  // No fetch logic — the matching `STATIC_REGIONS` entries in
  // `src/data/statics.json.ts` carry the typical-shape × annual-TWh dispatch.
  // lat/lon are capital-city coordinates unless noted otherwise.
  { id: "tva",                name: "TVA (SE United States)", country: "USA", lat: 35.5, lon:  -86.6, tier: "static", kind: "solar", source: "TVA Sustainability Report 2024 (provisional 0.05 TWh/yr; SE-US solar curtailment; TVA JSON-API path documented for future Pattern-A promotion)", sourceUrl: "https://www.tva.com/" },
  { id: "guatemala",          name: "Guatemala",            country: "GTM", lat: 14.6, lon:  -90.5, tier: "static", kind: "solar", source: "IRENA Renewable Energy Statistics 2024 (Guatemala VRE share) + AMM Plan Operativo 2024", sourceUrl: "https://www.amm.org.gt/" },
  { id: "el-salvador",        name: "El Salvador",          country: "SLV", lat: 13.7, lon:  -89.2, tier: "static", kind: "solar", source: "IRENA Renewable Energy Statistics 2024 (El Salvador VRE share)", sourceUrl: "https://www.ut.com.sv/" },
  { id: "nicaragua",          name: "Nicaragua",            country: "NIC", lat: 12.1, lon:  -86.3, tier: "static", kind: "solar", source: "IRENA Nicaragua VRE statistics 2024 (CNDC/ENATREL weekly bulletins)", sourceUrl: "https://www.enatrel.gob.ni/" },
  { id: "costa-rica",         name: "Costa Rica",           country: "CRI", lat: 9.93, lon:  -84.1, tier: "static", kind: "hydro", source: "IRENA Costa Rica 2024 (98% renewable; hydro spill not anchored to hourly feed; ICE/CENCE)", sourceUrl: "https://www.grupoice.com/" },
  { id: "panama",             name: "Panama",               country: "PAN", lat: 8.98, lon:  -79.5, tier: "static", kind: "solar", source: "Secretaria Nacional de Energia 2024 (solar+wind ~10%; ETESA/CND PDF reports)", sourceUrl: "https://www.etesa.com.pa/" },
  { id: "guatemala-siepac",   name: "Central America (SIEPAC)", country: "GTM", lat: 13.7, lon:  -86.0, tier: "static", kind: "solar", source: "IRENA Central America Interconnect 2024 (SIEPAC corridor; EOR Ente Operador Regional)", sourceUrl: "https://www.enteoperador.org/" },
  { id: "cuba",               name: "Cuba",                 country: "CUB", lat: 23.1, lon:  -82.4, tier: "static", kind: "mixed", source: "Cuba UNE 2022-24 grid restoration + Ember Cuba Electricity Review 2024 (post-Hurricane-Ian grid stress; not steady-state anchor)", sourceUrl: "https://www.une.cu/" },
  { id: "dominican-republic", name: "Dominican Republic",   country: "DOM", lat: 18.5, lon:  -69.9, tier: "static", kind: "solar", source: "IRENA Dominican Republic 2024 + OC (Organismo Coordinador del SENI) Reportes de Operacion 2024. Live promotion attempt 2026-04-29 reverted: OC `GetGeneracionReprogramadaJSon` endpoint exposes scheduled/actual total generation, not renewable-specific curtailed-energy. Held at T3 pending a genuine curtailment source.", sourceUrl: "https://www.oc.org.do/" },
  { id: "jamaica",            name: "Jamaica",              country: "JAM", lat: 18.0, lon:  -76.8, tier: "static", kind: "solar", source: "Office of Utilities Regulation Jamaica Annual Report 2024 (Wigton wind + Content solar)", sourceUrl: "https://www.jpsco.com/" },
  { id: "trinidad-tobago",    name: "Trinidad & Tobago",    country: "TTO", lat: 10.7, lon:  -61.5, tier: "static", kind: "flare", source: "GGFR 2024 Trinidad offshore flares ~1 BCM (upstream offshore flare lifted onto T&TEC grid coverage)", sourceUrl: "https://ttec.co.tt/" },
  { id: "barbados",           name: "Barbados",             country: "BRB", lat: 13.1, lon:  -59.6, tier: "static", kind: "solar", source: "IRENA Barbados Renewables 2024 (rooftop PV; at inclusion threshold)", sourceUrl: "https://www.blpc.com.bb/" },
  { id: "bolivia",            name: "Bolivia",              country: "BOL", lat: -16.5, lon: -68.2, tier: "static", kind: "solar", source: "IRENA Bolivia 2024 (hydro+gas dominated grid; solar+wind ~3% of mix; CNDC PDF reports)", sourceUrl: "https://www.cndc.bo/" },
  { id: "ecuador",            name: "Ecuador",              country: "ECU", lat: -0.18, lon: -78.5, tier: "static", kind: "hydro", source: "IRENA Ecuador 2024 (hydro-dominated; CENACE Ecuador PDF reports; at inclusion threshold)", sourceUrl: "https://www.cenace.gob.ec/" },
  { id: "guyana",             name: "Guyana",               country: "GUY", lat: 6.80, lon:  -58.2, tier: "static", kind: "flare", source: "GGFR 2024 Guyana Stabroek block flaring offshore (Liza FPSO; upstream off-grid lifted onto GPL coverage)", sourceUrl: "https://www.gplinc.com/" },
  { id: "suriname",           name: "Suriname",             country: "SUR", lat: 5.85, lon:  -55.2, tier: "static", kind: "flare", source: "GGFR 2024 Suriname Block 58 offshore flaring forecast (upstream off-grid; at inclusion threshold)", sourceUrl: "https://www.nvebs.com/" },
  { id: "french-guiana",      name: "French Guiana",        country: "GUF", lat: 4.92, lon:  -52.3, tier: "static", kind: "solar", source: "EDF SEI Bilan Previsionnel Guyane 2024 (below normal inclusion threshold; included for completeness as the only South-American French overseas territory)", sourceUrl: "https://www.edf.fr/edf-sei/" },
  // Phase-2.7 Pattern-D — Africa bulk-add (2026-04-27).
  // 32 audit rows tagged `recommended_action: introduce-as-T3` in
  // `data/coverage-audit/2026-04-26-africa.csv`; 6 sub-0.05 TWh rows skipped
  // (Burundi, Gambia, Lesotho, Liberia, Seychelles, Sierra Leone). Net 26
  // T3-modelled statics; ~11.7 TWh aggregate anchor. ±40% envelope.
  // Lat/lon = capital city by default (operator-published curtailment is
  // country-level, not zone-level, so a single capital point is the most
  // honest representation). Region.kind reflects the dominant fuel of the
  // grid; the StaticSpec.kind in src/data/statics.json.ts may collapse
  // hydro/mixed to a flat profile when no curated seasonal-share data is
  // available — both still land at T3-modelled.
  // See `docs/proposals/2026-04-27-phase-2-7-pattern-d-dispatch.md` §3 +
  // §4 CODEX-PHASE27-AFR for the canonical pattern.
  { id: "algeria",          name: "Algeria",           country: "DZA", lat:  36.75, lon:    3.06, tier: "static", kind: "solar", source: "IRENA Country Statistics 2024 (Algeria SONELGAZ/OS, ~1.5 GW wind+PV)", sourceUrl: "https://www.grte.dz/" },
  { id: "angola",           name: "Angola",            country: "AGO", lat:  -8.84, lon:   13.23, tier: "static", kind: "solar", source: "IRENA Angola 2024 (RNT transmission; nascent solar)", sourceUrl: "https://www.rnt.co.ao/" },
  { id: "benin",            name: "Benin",             country: "BEN", lat:   6.37, lon:    2.39, tier: "static", kind: "solar", source: "IRENA Benin 2024 (SBEE; imports ~80% via WAPP)", sourceUrl: "https://sbee.bj/" },
  { id: "botswana",         name: "Botswana",          country: "BWA", lat: -24.65, lon:   25.91, tier: "static", kind: "solar", source: "IRENA Botswana 2024 (BPC; SAPP member; Mmadinare PV)", sourceUrl: "https://www.bpc.bw/" },
  { id: "burkina-faso",     name: "Burkina Faso",      country: "BFA", lat:  12.37, lon:   -1.52, tier: "static", kind: "solar", source: "IRENA Burkina Faso 2024 (SONABEL; Zagtouli + Nagreongo PV ~70 MW)", sourceUrl: "https://www.sonabel.bf/" },
  { id: "cabo-verde",       name: "Cabo Verde",        country: "CPV", lat:  14.93, lon:  -23.51, tier: "static", kind: "solar", source: "IRENA Cabo Verde 2024 (ELECTRA; 9-island system; high VRE)", sourceUrl: "https://www.electra.cv/" },
  { id: "cameroon",         name: "Cameroon",          country: "CMR", lat:   3.85, lon:   11.50, tier: "static", kind: "hydro", source: "IRENA Cameroon 2024 (ENEO/SONATREL; mostly hydro)", sourceUrl: "https://eneo.cm/" },
  { id: "congo-drc",        name: "DR Congo",          country: "COD", lat:  -4.32, lon:   15.32, tier: "static", kind: "hydro", source: "IRENA DRC 2024 (SNEL; Inga hydro complex ~2.5 GW; SAPP)", sourceUrl: "https://www.snel.cd/" },
  { id: "cote-divoire",     name: "Cote d'Ivoire",     country: "CIV", lat:   5.32, lon:   -4.02, tier: "static", kind: "solar", source: "IRENA Cote d'Ivoire 2024 (CIE; major WAPP exporter)", sourceUrl: "https://www.cie.ci/" },
  { id: "eswatini",         name: "Eswatini",          country: "SWZ", lat: -26.31, lon:   31.13, tier: "static", kind: "solar", source: "IRENA Eswatini 2024 (EEC; SAPP member; biomass+hydro)", sourceUrl: "https://www.eec.co.sz/" },
  { id: "gabon",            name: "Gabon",             country: "GAB", lat:   0.42, lon:    9.45, tier: "static", kind: "hydro", source: "IRENA Gabon 2024 (SEEG; hydro+gas; flaring relevant)", sourceUrl: "https://www.seeg-gabon.com/" },
  { id: "ghana",            name: "Ghana",             country: "GHA", lat:   5.61, lon:   -0.20, tier: "static", kind: "solar", source: "Ember Ghana 2024 (GRIDCo TSO; Akosombo hydro + PV)", sourceUrl: "https://www.gridcogh.com/" },
  { id: "madagascar",       name: "Madagascar",        country: "MDG", lat: -18.88, lon:   47.51, tier: "static", kind: "hydro", source: "IRENA Madagascar 2024 (JIRAMA; hydro+thermal isolated grids)", sourceUrl: "https://www.jirama.mg/" },
  { id: "malawi",           name: "Malawi",            country: "MWI", lat: -13.95, lon:   33.78, tier: "static", kind: "hydro", source: "IRENA Malawi 2024 (ESCOM/EGENCO; Shire hydro + Salima PV; SAPP)", sourceUrl: "https://www.escom.mw/" },
  { id: "mauritania",       name: "Mauritania",        country: "MRT", lat:  18.07, lon:  -15.97, tier: "static", kind: "wind",  source: "IRENA Mauritania 2024 (SOMELEC; Boulenouar wind 100 MW + Sheikh Zayed PV)", sourceUrl: "https://somelec.mr/" },
  { id: "mauritius",        name: "Mauritius",         country: "MUS", lat: -20.16, lon:   57.51, tier: "static", kind: "solar", source: "IRENA Mauritius 2024 (CEB; bagasse+coal+oil + PV; island)", sourceUrl: "https://ceb.mu/" },
  { id: "mozambique",       name: "Mozambique",        country: "MOZ", lat: -25.97, lon:   32.58, tier: "static", kind: "hydro", source: "IRENA Mozambique 2024 (EDM; Cahora Bassa hydro; SAPP)", sourceUrl: "https://www.edm.co.mz/" },
  { id: "nigeria",          name: "Nigeria",           country: "NGA", lat:   9.00, lon:    8.50, tier: "static", kind: "solar", source: "Ember Nigeria 2024 + TCN 2024 (solar curtailment; Niger Delta flare ~7 TWh-eq/yr is a separate flat-baseload signal)", sourceUrl: "https://www.tcn.org.ng/" },
  { id: "rwanda",           name: "Rwanda",            country: "RWA", lat:  -1.94, lon:   30.06, tier: "static", kind: "mixed", source: "IRENA Rwanda 2024 (REG/EUCL; Lake Kivu methane + hydro+solar)", sourceUrl: "https://www.reg.rw/" },
  { id: "senegal",          name: "Senegal",           country: "SEN", lat:  14.69, lon:  -17.45, tier: "static", kind: "solar", source: "IRENA Senegal 2024 (SENELEC; Taiba N'Diaye 158 MW wind + PV)", sourceUrl: "https://www.senelec.sn/" },
  { id: "tanzania",         name: "Tanzania",          country: "TZA", lat:  -6.79, lon:   39.21, tier: "static", kind: "hydro", source: "IRENA Tanzania 2024 + JNHPP commissioning (TANESCO; gas+hydro)", sourceUrl: "https://www.tanesco.co.tz/" },
  { id: "togo",             name: "Togo",              country: "TGO", lat:   6.13, lon:    1.22, tier: "static", kind: "solar", source: "IRENA Togo 2024 (CEET; WAPP imports; Blitta PV 50 MW)", sourceUrl: "https://ceet.tg/" },
  { id: "tunisia",          name: "Tunisia",           country: "TUN", lat:  36.81, lon:   10.18, tier: "static", kind: "solar", source: "IRENA Tunisia 2024 + STEG Annual Report (Bizerte wind + PV; gas-dominated)", sourceUrl: "https://www.steg.com.tn/" },
  { id: "uganda",           name: "Uganda",            country: "UGA", lat:   0.32, lon:   32.58, tier: "static", kind: "hydro", source: "ERA Annual Performance 2024 (UETCL/UEDCL; Karuma+Isimba hydro)", sourceUrl: "https://www.uetcl.com/" },
  { id: "zambia",           name: "Zambia",            country: "ZMB", lat: -15.42, lon:   28.28, tier: "static", kind: "hydro", source: "Ember Zambia 2024 + Kariba drought (ZESCO; Kariba+Kafue; severe drought load-shed; SAPP)", sourceUrl: "https://www.zesco.co.zm/" },
  { id: "zimbabwe",         name: "Zimbabwe",          country: "ZWE", lat: -17.83, lon:   31.05, tier: "static", kind: "hydro", source: "Ember Zimbabwe 2024 + Kariba South (ZPC/ZETDC; Kariba South hydro+coal; SAPP)", sourceUrl: "https://www.zetdc.co.zw/" },
  // Tier 3 - flare (8 regions)
  { id: "permian",   name: "Permian Basin",   country: "USA",    lat:  31.9, lon: -102.5, tier: "flare",  kind: "flare", source: "VIIRS + GGFR", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "w-siberia", name: "W. Siberia",      country: "RUS",    lat:  61.0, lon:   73.0, tier: "flare",  kind: "flare", source: "VIIRS + GGFR", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "s-iraq",    name: "S. Iraq",         country: "IRQ",    lat:  30.5, lon:   47.5, tier: "flare",  kind: "flare", source: "VIIRS + GGFR", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "e-saudi",   name: "E. Saudi Arabia", country: "SAU",    lat:  26.5, lon:   49.5, tier: "flare",  kind: "flare", source: "VIIRS + GGFR", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "qatar",     name: "Qatar",           country: "QAT",    lat:  25.3, lon:   51.5, tier: "flare",  kind: "flare", source: "GGFR 2024 Qatar offshore+onshore flare composite (QatarEnergy)", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "kuwait",    name: "Kuwait",          country: "KWT",    lat:  29.0, lon:   47.7, tier: "flare",  kind: "flare", source: "GGFR 2024 Kuwait Burgan + Wafra flare composite (KOC)", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "russia-yamal",     name: "Yamal (flare)",     country: "RUS", lat:  68.0, lon:   68.5, tier: "flare",  kind: "flare", source: "GGFR 2024 Yamal-Nenets gas flaring (Gazprom/Novatek)", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" },
  { id: "russia-e-siberia", name: "E. Siberia (flare)", country: "RUS", lat:  62.0, lon:  107.0, tier: "flare",  kind: "flare", source: "GGFR 2024 East Siberia oil/gas flaring (ESPO corridor + Sakhalin)", sourceUrl: "https://www.worldbank.org/en/programs/gasflaringreduction" }
];
