import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  parseEskomDataPortal,
  parseEskomTotalHourlyGeneration,
  buildEskomCsvCandidates,
  resolveEskomCsv,
  scrapeEskomCsvUrl,
} from "../../src/data/south-africa.json";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = readFileSync(join(__dirname, "../fixtures/south-africa-sample.html"), "utf8");

describe("south africa parser (Eskom portal)", () => {
  it("extracts the portal title", () => {
    const result = parseEskomDataPortal(fixture);
    expect(result.title).toContain("Eskom Data Portal");
  });
});

// ---------------------------------------------------------------------------
// buildEskomCsvCandidates
// ---------------------------------------------------------------------------

describe("buildEskomCsvCandidates", () => {
  it("puts the scraped URL first, then walks back from the current UTC month", () => {
    const now = new Date("2026-08-19T12:00:00Z");
    const scraped = "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/07/Total_Hourly_Generation.csv";
    const candidates = buildEskomCsvCandidates(scraped, now, 3);

    expect(candidates[0]).toBe(scraped);
    // scraped (07) is also generated by the back-walk, so it de-dupes to a
    // single entry at the front rather than appearing twice.
    expect(candidates).toEqual([
      scraped,
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/06/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/05/Total_Hourly_Generation.csv",
    ]);
  });

  it("de-duplicates when the scraped URL matches a generated month path", () => {
    const now = new Date("2026-08-19T12:00:00Z");
    // Scraped URL happens to already be the current-month path.
    const scraped = "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv";
    const candidates = buildEskomCsvCandidates(scraped, now, 3);

    // Should appear exactly once, at the front.
    expect(candidates.filter((c) => c === scraped)).toHaveLength(1);
    expect(candidates[0]).toBe(scraped);
    expect(candidates).toHaveLength(4); // current month + 3 back, scraped merged into current-month slot
  });

  it("omits the scraped slot entirely when nothing was scraped", () => {
    const now = new Date("2026-08-19T12:00:00Z");
    const candidates = buildEskomCsvCandidates("", now, 3);

    expect(candidates).toEqual([
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/07/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/06/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/05/Total_Hourly_Generation.csv",
    ]);
  });

  it("rolls the year over correctly when walking back across a January boundary", () => {
    const now = new Date("2026-01-15T00:00:00Z");
    const candidates = buildEskomCsvCandidates("", now, 2);

    expect(candidates).toEqual([
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/01/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2025/12/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2025/11/Total_Hourly_Generation.csv",
    ]);
  });
});

// ---------------------------------------------------------------------------
// resolveEskomCsv
// ---------------------------------------------------------------------------

const SAMPLE_CSV = [
  "Date Time Hour Beginning,Wind,PV,CSP,Other_RE",
  "2026-08-01 00:00:00,120,0,0,0",
  "2026-08-01 01:00:00,140,0,5,0",
].join("\n");

const ALL_ZERO_CSV = [
  "Date Time Hour Beginning,Wind,PV,CSP,Other_RE",
  "2026-08-31 00:00:00,0,0,0,0",
  "2026-08-31 01:00:00,0,0,0,0",
].join("\n");

describe("resolveEskomCsv", () => {
  it("accepts the first candidate that fetches and parses successfully", async () => {
    const now = new Date("2026-08-01T02:00:00Z"); // just after SAMPLE_CSV's newest point
    const fetchFn = async (url: string) => {
      expect(url).toBe("https://example.com/2026/08/Total_Hourly_Generation.csv");
      return SAMPLE_CSV;
    };
    const { url, parsed } = await resolveEskomCsv(
      ["https://example.com/2026/08/Total_Hourly_Generation.csv"],
      fetchFn,
      now,
    );
    expect(url).toBe("https://example.com/2026/08/Total_Hourly_Generation.csv");
    expect(parsed.windPoints.length).toBeGreaterThan(0);
  });

  it("falls through to the next candidate when the first 404s", async () => {
    const now = new Date("2026-08-01T02:00:00Z"); // just after SAMPLE_CSV's newest point
    const attempted: string[] = [];
    const fetchFn = async (url: string) => {
      attempted.push(url);
      if (url.includes("2026/07")) throw new Error("HTTP 404 for " + url);
      return SAMPLE_CSV;
    };

    const { url, parsed } = await resolveEskomCsv(
      [
        "https://example.com/2026/07/Total_Hourly_Generation.csv",
        "https://example.com/2026/06/Total_Hourly_Generation.csv",
      ],
      fetchFn,
      now,
    );

    expect(attempted).toEqual([
      "https://example.com/2026/07/Total_Hourly_Generation.csv",
      "https://example.com/2026/06/Total_Hourly_Generation.csv",
    ]);
    expect(url).toBe("https://example.com/2026/06/Total_Hourly_Generation.csv");
    expect(parsed.windPoints.length).toBeGreaterThan(0);
  });

  it("falls through a candidate that fetches but parses to zero usable points", async () => {
    const now = new Date("2026-08-01T02:00:00Z"); // just after SAMPLE_CSV's newest point
    const fetchFn = async (url: string) => {
      if (url.includes("2026/08/31")) return ALL_ZERO_CSV;
      return SAMPLE_CSV;
    };

    const { url } = await resolveEskomCsv(
      [
        "https://example.com/2026/08/31/Total_Hourly_Generation.csv",
        "https://example.com/2026/07/Total_Hourly_Generation.csv",
      ],
      fetchFn,
      now,
    );

    expect(url).toBe("https://example.com/2026/07/Total_Hourly_Generation.csv");
  });

  it("throws (does not silently succeed) when every candidate fails", async () => {
    const fetchFn = async (url: string) => {
      throw new Error("HTTP 404 for " + url);
    };

    await expect(
      resolveEskomCsv(
        [
          "https://example.com/2026/08/Total_Hourly_Generation.csv",
          "https://example.com/2026/07/Total_Hourly_Generation.csv",
        ],
        fetchFn,
      ),
    ).rejects.toThrow(/Eskom CSV unresolved/);
  });

  // -------------------------------------------------------------------------
  // Freshness comparison (the review finding this PR update addresses): a
  // stale-but-parsing first candidate must lose to a fresher later one, and
  // a current first candidate must short-circuit without fetching the rest.
  // -------------------------------------------------------------------------

  const STALE_CSV = [
    "Date Time Hour Beginning,Wind,PV,CSP,Other_RE",
    "2026-06-01 00:00:00,100,0,0,0",
    "2026-06-01 01:00:00,110,0,0,0",
  ].join("\n");

  const FRESH_CSV = [
    "Date Time Hour Beginning,Wind,PV,CSP,Other_RE",
    "2026-08-19 08:00:00,150,20,0,0",
    "2026-08-19 09:00:00,160,25,0,0",
  ].join("\n");

  it("picks the freshest candidate, not the first that merely parses", async () => {
    const now = new Date("2026-08-19T10:00:00Z"); // 1-2h after FRESH_CSV's newest point
    const attempted: string[] = [];
    const fetchFn = async (url: string) => {
      attempted.push(url);
      if (url.includes("scraped-stale")) return STALE_CSV;
      return FRESH_CSV;
    };

    const { url, newestTimestamp } = await resolveEskomCsv(
      [
        "https://example.com/scraped-stale/Total_Hourly_Generation.csv", // stale portal link, still parses
        "https://example.com/2026/08/Total_Hourly_Generation.csv", // fresher computed candidate
      ],
      fetchFn,
      now,
    );

    // Both candidates get fetched — the stale one alone isn't "current
    // enough" to short-circuit — and the freshest wins.
    expect(attempted).toEqual([
      "https://example.com/scraped-stale/Total_Hourly_Generation.csv",
      "https://example.com/2026/08/Total_Hourly_Generation.csv",
    ]);
    expect(url).toBe("https://example.com/2026/08/Total_Hourly_Generation.csv");
    expect(newestTimestamp > "2026-06-01T01:00:00.000Z").toBe(true);
  });

  it("short-circuits on a current first candidate without fetching the rest", async () => {
    const now = new Date("2026-08-19T10:00:00Z"); // 1-2h after FRESH_CSV's newest point
    const attempted: string[] = [];
    const fetchFn = async (url: string) => {
      attempted.push(url);
      return FRESH_CSV;
    };

    const { url } = await resolveEskomCsv(
      [
        "https://example.com/2026/08/Total_Hourly_Generation.csv", // current — should short-circuit
        "https://example.com/2026/07/Total_Hourly_Generation.csv",
        "https://example.com/2026/06/Total_Hourly_Generation.csv",
      ],
      fetchFn,
      now,
    );

    expect(attempted).toEqual(["https://example.com/2026/08/Total_Hourly_Generation.csv"]);
    expect(url).toBe("https://example.com/2026/08/Total_Hourly_Generation.csv");
  });
});

// ---------------------------------------------------------------------------
// parseEskomTotalHourlyGeneration (regression: preserve zero-row skip)
// ---------------------------------------------------------------------------

describe("parseEskomTotalHourlyGeneration", () => {
  it("skips all-zero rows (pre-filled future hours)", () => {
    const result = parseEskomTotalHourlyGeneration(ALL_ZERO_CSV);
    expect(result.windPoints).toHaveLength(0);
    expect(result.solarPoints).toHaveLength(0);
  });

  it("emits points for rows with non-zero generation", () => {
    const result = parseEskomTotalHourlyGeneration(SAMPLE_CSV);
    expect(result.windPoints.length).toBe(2);
    // Both rows are kept (row 1 has wind, row 2 has wind+CSP), each row
    // emits a solar entry too (0 MW when only wind is present that hour).
    expect(result.solarPoints.length).toBe(2);
    expect(result.solarPoints.some((p) => p.mw > 0)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// scrapeEskomCsvUrl (portal page must not be a single point of failure)
// ---------------------------------------------------------------------------

describe("scrapeEskomCsvUrl", () => {
  it("returns the scraped csvUrl when the page fetches and parses fine", async () => {
    const fetchPageFn = async () => fixture;
    const url = await scrapeEskomCsvUrl(fetchPageFn);
    // The fixture doesn't contain a literal CSV link, so parseEskomDataPortal
    // legitimately returns "" here — the point of this test is that a
    // successful fetch+parse path returns without throwing.
    expect(typeof url).toBe("string");
  });

  it("resolves to \"\" (not a rejection) when the page fetch throws", async () => {
    const fetchPageFn = async () => {
      throw new Error("HTTP 503 for portal page");
    };
    const url = await scrapeEskomCsvUrl(fetchPageFn);
    expect(url).toBe("");
  });

  it("resolves to \"\" (not a rejection) when the page HTML has no <title>", async () => {
    const fetchPageFn = async () => "<html><body>no title here</body></html>";
    const url = await scrapeEskomCsvUrl(fetchPageFn);
    expect(url).toBe("");
  });

  it("end-to-end: a failed portal fetch still lets the loader resolve via a computed candidate", async () => {
    // Simulates the exact gap this test guards against: the portal page is
    // down, but buildEskomCsvCandidates("") + resolveEskomCsv still finds
    // a working CSV among the computed month candidates.
    const fetchPageFn = async () => {
      throw new Error("portal unreachable");
    };
    const scrapedUrl = await scrapeEskomCsvUrl(fetchPageFn);
    expect(scrapedUrl).toBe("");

    const now = new Date("2026-08-19T12:00:00Z");
    const candidates = buildEskomCsvCandidates(scrapedUrl, now, 3);
    expect(candidates).toEqual([
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/07/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/06/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/05/Total_Hourly_Generation.csv",
    ]);

    const csvFetchFn = async (url: string) => {
      if (url.includes("2026/08")) return SAMPLE_CSV;
      throw new Error("HTTP 404 for " + url);
    };
    const { url, parsed } = await resolveEskomCsv(candidates, csvFetchFn);
    expect(url).toContain("2026/08");
    expect(parsed.windPoints.length).toBeGreaterThan(0);
  });
});
