import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  parseEskomDataPortal,
  parseEskomTotalHourlyGeneration,
  buildEskomCsvCandidates,
  resolveEskomCsv,
} from "../../src/data/south-africa.json";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = readFileSync(join(__dirname, "../fixtures/south-africa-sample.html"), "utf8");

describe("south africa parser (Eskom portal)", () => {
  it("extracts the portal title", () => {
    const result = parseEskomDataPortal(fixture);
    expect(result.title).toContain("Eskom Data Portal");
  });
});

// ---------------------------------------------------------------------------
// buildEskomCsvCandidates
// ---------------------------------------------------------------------------

describe("buildEskomCsvCandidates", () => {
  it("puts the scraped URL first, then walks back from the current UTC month", () => {
    const now = new Date("2026-08-19T12:00:00Z");
    const scraped = "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/07/Total_Hourly_Generation.csv";
    const candidates = buildEskomCsvCandidates(scraped, now, 3);

    expect(candidates[0]).toBe(scraped);
    // scraped (07) is also generated by the back-walk, so it de-dupes to a
    // single entry at the front rather than appearing twice.
    expect(candidates).toEqual([
      scraped,
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/06/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/05/Total_Hourly_Generation.csv",
    ]);
  });

  it("de-duplicates when the scraped URL matches a generated month path", () => {
    const now = new Date("2026-08-19T12:00:00Z");
    // Scraped URL happens to already be the current-month path.
    const scraped = "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv";
    const candidates = buildEskomCsvCandidates(scraped, now, 3);

    // Should appear exactly once, at the front.
    expect(candidates.filter((c) => c === scraped)).toHaveLength(1);
    expect(candidates[0]).toBe(scraped);
    expect(candidates).toHaveLength(4); // current month + 3 back, scraped merged into current-month slot
  });

  it("omits the scraped slot entirely when nothing was scraped", () => {
    const now = new Date("2026-08-19T12:00:00Z");
    const candidates = buildEskomCsvCandidates("", now, 3);

    expect(candidates).toEqual([
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/08/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/07/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/06/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/05/Total_Hourly_Generation.csv",
    ]);
  });

  it("rolls the year over correctly when walking back across a January boundary", () => {
    const now = new Date("2026-01-15T00:00:00Z");
    const candidates = buildEskomCsvCandidates("", now, 2);

    expect(candidates).toEqual([
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2026/01/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2025/12/Total_Hourly_Generation.csv",
      "https://www.eskom.co.za/dataportal/wp-content/uploads/2025/11/Total_Hourly_Generation.csv",
    ]);
  });
});

// ---------------------------------------------------------------------------
// resolveEskomCsv
// ---------------------------------------------------------------------------

const SAMPLE_CSV = [
  "Date Time Hour Beginning,Wind,PV,CSP,Other_RE",
  "2026-08-01 00:00:00,120,0,0,0",
  "2026-08-01 01:00:00,140,0,5,0",
].join("\n");

const ALL_ZERO_CSV = [
  "Date Time Hour Beginning,Wind,PV,CSP,Other_RE",
  "2026-08-31 00:00:00,0,0,0,0",
  "2026-08-31 01:00:00,0,0,0,0",
].join("\n");

describe("resolveEskomCsv", () => {
  it("accepts the first candidate that fetches and parses successfully", async () => {
    const fetchFn = async (url: string) => {
      expect(url).toBe("https://example.com/2026/08/Total_Hourly_Generation.csv");
      return SAMPLE_CSV;
    };
    const { url, parsed } = await resolveEskomCsv(
      ["https://example.com/2026/08/Total_Hourly_Generation.csv"],
      fetchFn,
    );
    expect(url).toBe("https://example.com/2026/08/Total_Hourly_Generation.csv");
    expect(parsed.windPoints.length).toBeGreaterThan(0);
  });

  it("falls through to the next candidate when the first 404s", async () => {
    const attempted: string[] = [];
    const fetchFn = async (url: string) => {
      attempted.push(url);
      if (url.includes("2026/07")) throw new Error("HTTP 404 for " + url);
      return SAMPLE_CSV;
    };

    const { url, parsed } = await resolveEskomCsv(
      [
        "https://example.com/2026/07/Total_Hourly_Generation.csv",
        "https://example.com/2026/06/Total_Hourly_Generation.csv",
      ],
      fetchFn,
    );

    expect(attempted).toEqual([
      "https://example.com/2026/07/Total_Hourly_Generation.csv",
      "https://example.com/2026/06/Total_Hourly_Generation.csv",
    ]);
    expect(url).toBe("https://example.com/2026/06/Total_Hourly_Generation.csv");
    expect(parsed.windPoints.length).toBeGreaterThan(0);
  });

  it("falls through a candidate that fetches but parses to zero usable points", async () => {
    const fetchFn = async (url: string) => {
      if (url.includes("2026/08/31")) return ALL_ZERO_CSV;
      return SAMPLE_CSV;
    };

    const { url } = await resolveEskomCsv(
      [
        "https://example.com/2026/08/31/Total_Hourly_Generation.csv",
        "https://example.com/2026/07/Total_Hourly_Generation.csv",
      ],
      fetchFn,
    );

    expect(url).toBe("https://example.com/2026/07/Total_Hourly_Generation.csv");
  });

  it("throws (does not silently succeed) when every candidate fails", async () => {
    const fetchFn = async (url: string) => {
      throw new Error("HTTP 404 for " + url);
    };

    await expect(
      resolveEskomCsv(
        [
          "https://example.com/2026/08/Total_Hourly_Generation.csv",
          "https://example.com/2026/07/Total_Hourly_Generation.csv",
        ],
        fetchFn,
      ),
    ).rejects.toThrow(/Eskom CSV unresolved/);
  });
});

// ---------------------------------------------------------------------------
// parseEskomTotalHourlyGeneration (regression: preserve zero-row skip)
// ---------------------------------------------------------------------------

describe("parseEskomTotalHourlyGeneration", () => {
  it("skips all-zero rows (pre-filled future hours)", () => {
    const result = parseEskomTotalHourlyGeneration(ALL_ZERO_CSV);
    expect(result.windPoints).toHaveLength(0);
    expect(result.solarPoints).toHaveLength(0);
  });

  it("emits points for rows with non-zero generation", () => {
    const result = parseEskomTotalHourlyGeneration(SAMPLE_CSV);
    expect(result.windPoints.length).toBe(2);
    // Both rows are kept (row 1 has wind, row 2 has wind+CSP), each row
    // emits a solar entry too (0 MW when only wind is present that hour).
    expect(result.solarPoints.length).toBe(2);
    expect(result.solarPoints.some((p) => p.mw > 0)).toBe(true);
  });
});
